print("Tu nombre por favor ")
nombre = input()
print("Brindamos el curso ")
curso = input()
print("Hola " + nombre + " Determinaremos tu nota final en el curso de " + curso)
print ("Brindanos tus tres notas parciales")
print ("Primera nota")
parcial_1 = int(input())
print("Segunda nota")
parcial_2 = int(input())
print("Tercer nota")
parcial_3 = int(input())
promedioParcialNota = ((parcial_1+parcial_2+parcial_3)/3)
print("Brindanos la nota de tu  trabajo final")
trabajoFinal = int(input())
print("Brindanos la nota de tu examen final ")
examenFinal = int(input())
porcentajeParcialNota = int(promedioParcialNota*0.55)
procentajeExamenFinal=int(examenFinal*0.30)
procentajeTrabajoFinal = int(trabajoFinal * 0.15) 
print(nombre + " Tu nota en la materia de " + curso + " es " + str(porcentajeParcialNota+procentajeExamenFinal+procentajeTrabajoFinal))
