print("Determinaremos tiempo de alcance")
print("Introduzca la velocidad del primer vehículo")
x = int(input())
print("La primera velocidad " + str(x) + " km/h" )
print("Inroduzca la velocidad del segundo vehículo")
y = int(input())
print("La segunda velocidad es " + str(y) + " km/h")
print("Distancia entre los dos vehículos ")
z = int(input())
print("La distancia es " + str(z)  + " km")
tiempo = (z)/(x+y)
minutos = (tiempo*60) 
print("El tiempo de alcance es " + str(minutos) + " minutos ")
