print("Calcular la media")
print("primer número")
x = int(input())
print("segundo número")
y = int(input())
print("tercer número")
z = int(input())
media = ((x+y+z)/3)
print("La media es " + str(media))
